
server:
  port: 8082
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/catalog-book
    username: admin
    password: PO_postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hobernate.dialect.PostgreSQLDialect
    jdbc: 
        lob.non-contextual-creation: true
        type:
          descriptor:
            sql:trace
#Configuração para windows terminal padrao de cores            
  output:
    ansi:
      enabled: always

logging:
  level:
    '[br.com.apassu]': trace
    root: info
    '[org.springframework.web]': debug
    '[org.hibernate]': info
    
